-- +goose Up
-- +goose StatementBegin
-- Intentional no-op. This version number was previously occupied by
-- 00021_create_saml_configs.sql on master; any DB that applied that version
-- will skip this file. The actual schema change lives in
-- 00039_users_email_verified_token_version.sql, which is append-only and safe
-- to run on any existing database.
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- +goose StatementEnd
