-- +goose NO TRANSACTION
--
-- Runs outside a transaction: the backfill COMMITs between batches, and
-- CREATE INDEX CONCURRENTLY cannot run inside a transaction block.

-- +goose Up
-- +goose StatementBegin

-- Promote the session to a first-class entity.
--
-- Until now a "session" was implicit: the set of refresh_tokens rows sharing a
-- session_family_id. That worked, but it made the session's own facts —
-- authentication time, methods used, both expiry clocks, whether the user asked to
-- be remembered — properties of a CREDENTIAL, copied onto every new token row at
-- each rotation. Three costs followed, and all three are structural rather than
-- fixable in place:
--
--   1. Copy-forward drift. Every rotation had to carry a growing set of fields
--      forward by hand. A path that forgot one silently changed the session's
--      character — and rotation has three code paths (plain refresh, locked
--      refresh, grace).
--   2. Revocation correctness became a discipline. "Revoke this session" meant
--      "UPDATE every row matching family AND user AND tenant", and getting that
--      predicate wrong is how a replayed token could once have revoked family 0
--      across every tenant. With a parent row it is one write to one row.
--   3. Facts with no home. The family's absolute deadline had to be re-derived
--      from MIN(created_at), and application_id had nowhere to live at all.
--
-- Here the session is the parent and tokens are its credentials. Session state is
-- stored once; a token carries only what belongs to a token.
CREATE TABLE IF NOT EXISTS user_sessions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tenant_id      BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    -- Which application the session was established through. NULL for a
    -- tenant-level session (an owner or administrator signing into the console).
    -- Had nowhere to live under the old shape, which is why sessions could not be
    -- attributed to an application.
    application_id BIGINT REFERENCES oauth_clients(id) ON DELETE CASCADE,

    -- Device attribution, captured once at sign-in.
    --
    -- user_agent is the raw header; device_hint is the parsed "Chrome on Windows"
    -- form. Both, deliberately: the raw string is the evidence and must not be
    -- lost, while the hint means every consumer — not just our own frontend —
    -- gets something a human can read without shipping a UA parser.
    user_agent     TEXT NOT NULL DEFAULT '',
    device_hint    TEXT,
    ip_address     INET,

    -- Authentication context. One copy, on the session it describes.
    --
    -- auth_time is when the user actually proved who they were, which a rotation
    -- must never move; amr lists the methods used (OIDC "amr"). Together they
    -- answer "how strongly was this session authenticated, and how long ago" —
    -- required for OIDC max_age / prompt=login and for any step-up check.
    auth_time      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    amr            TEXT[] NOT NULL DEFAULT '{}',
    -- Whether the user asked to be remembered, selecting which idle clock applies.
    is_persistent  BOOLEAN NOT NULL DEFAULT false,

    -- The two lifetime clocks, now owned by the session rather than smeared across
    -- its tokens. idle slides forward on activity; absolute never moves.
    idle_expires_at     TIMESTAMPTZ NOT NULL,
    absolute_expires_at TIMESTAMPTZ NOT NULL,
    last_seen_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Ending a session is now a single write here.
    revoked_at     TIMESTAMPTZ,
    revoked_reason TEXT,

    -- An idle deadline past the absolute cap can never fire, which would silently
    -- restore the unbounded behaviour the idle clock exists to prevent.
    CONSTRAINT user_sessions_idle_within_absolute
        CHECK (idle_expires_at <= absolute_expires_at)
);

-- +goose StatementEnd

-- +goose StatementBegin

-- Tokens become children of the session.
--
-- Nullable rather than NOT NULL: a rolling deploy has the previous binary still
-- inserting rows that know nothing about this column, and failing those inserts
-- would take sign-in down for the duration. The application always sets it; the
-- reads tolerate NULL for exactly the length of a deploy.
ALTER TABLE refresh_tokens
    ADD COLUMN IF NOT EXISTS session_id BIGINT REFERENCES user_sessions(id) ON DELETE CASCADE;

-- +goose StatementEnd

-- +goose StatementBegin

-- Backfill one session per existing family, batched.
--
-- The session's id is set to the OLD session_family_id on purpose, and this is
-- load-bearing: the "sid" claim in every access token already in circulation holds
-- the family id. Allocating fresh ids would leave those tokens pointing at nothing,
-- so a single-session revoke would silently miss every session established before
-- the deploy — for the whole 15-minute life of each token. Reusing the id makes the
-- cutover invisible to tokens already issued.
--
-- GENERATED BY DEFAULT AS IDENTITY (not ALWAYS) is what permits the explicit id
-- here; the sequence is advanced past the highest value at the end.
CREATE OR REPLACE PROCEDURE emc_backfill_user_sessions()
LANGUAGE plpgsql AS $$
DECLARE
    batch_size CONSTANT INTEGER := 5000;
    touched    INTEGER;
BEGIN
    LOOP
        WITH families AS (
            SELECT rt.session_family_id AS id,
                   MIN(rt.user_id)      AS user_id,
                   MIN(rt.tenant_id)    AS tenant_id,
                   -- Aggregates over the family, since any row may carry the value.
                   -- The family is one user's, so MIN/MAX pick a consistent row.
                   MIN(rt.created_at)   AS created_at,
                   MAX(COALESCE(rt.last_used_at, rt.created_at)) AS last_seen_at,
                   MIN(COALESCE(rt.auth_time, rt.created_at))    AS auth_time,
                   MAX(rt.idle_expires_at)     AS idle_expires_at,
                   MAX(rt.absolute_expires_at) AS absolute_expires_at,
                   MAX(rt.expires_at)          AS expires_at,
                   BOOL_OR(rt.is_persistent)   AS is_persistent,
                   -- The newest row's device info is the freshest known.
                   --
                   -- amr is NOT aggregated this way: it is already text[], so
                   -- ARRAY_AGG would build a two-dimensional array whose [1]
                   -- subscript yields a single text element rather than the inner
                   -- array. It is fetched as a scalar subquery in the SELECT below.
                   (ARRAY_AGG(rt.user_agent ORDER BY rt.id DESC))[1] AS user_agent,
                   (ARRAY_AGG(rt.ip_address ORDER BY rt.id DESC))[1] AS ip_address,
                   -- Live iff at least one token in it is still usable. A family
                   -- whose every token is revoked or expired becomes a revoked
                   -- session, so it does not reappear as active.
                   BOOL_OR(rt.revoked_at IS NULL AND rt.expires_at > NOW()) AS live,
                   MAX(rt.revoked_at)     AS revoked_at,
                   (ARRAY_AGG(rt.revoked_reason ORDER BY rt.id DESC))[1] AS revoked_reason
            FROM refresh_tokens rt
            WHERE rt.session_id IS NULL
              AND rt.session_family_id <> 0
              AND EXISTS (SELECT 1 FROM users u WHERE u.id = rt.user_id)
              AND EXISTS (SELECT 1 FROM tenants t WHERE t.id = rt.tenant_id)
            GROUP BY rt.session_family_id
            LIMIT batch_size
        )
        INSERT INTO user_sessions
            (id, user_id, tenant_id, application_id, user_agent, ip_address,
             auth_time, amr, is_persistent, idle_expires_at, absolute_expires_at,
             last_seen_at, created_at, revoked_at, revoked_reason)
        SELECT f.id, f.user_id, f.tenant_id,
               -- Derived from the account, the only place it was recorded.
               (SELECT u.application_id FROM users u WHERE u.id = f.user_id),
               COALESCE(f.user_agent, ''), f.ip_address,
               f.auth_time,
               -- Newest row's amr, as a scalar subquery for the reason above.
               COALESCE(
                   (SELECT x.amr FROM refresh_tokens x
                     WHERE x.session_family_id = f.id ORDER BY x.id DESC LIMIT 1),
                   '{}'
               ),
               COALESCE(f.is_persistent, false),
               -- Legacy rows may carry neither clock. Derive both, then clamp idle
               -- to absolute so the CHECK above holds for every backfilled row.
               LEAST(
                   COALESCE(f.idle_expires_at, f.last_seen_at + INTERVAL '7 days'),
                   COALESCE(f.absolute_expires_at, f.expires_at, f.created_at + INTERVAL '30 days')
               ),
               COALESCE(f.absolute_expires_at, f.expires_at, f.created_at + INTERVAL '30 days'),
               f.last_seen_at, f.created_at,
               -- A family with no live token is recorded as ended, so the listing
               -- does not resurrect sessions that were already gone.
               CASE WHEN f.live THEN NULL ELSE COALESCE(f.revoked_at, NOW()) END,
               CASE WHEN f.live THEN NULL ELSE COALESCE(f.revoked_reason, 'migrated_dead') END
        FROM families f
        ON CONFLICT (id) DO NOTHING;

        GET DIAGNOSTICS touched = ROW_COUNT;

        -- Point the tokens at the sessions just created.
        UPDATE refresh_tokens rt
           SET session_id = rt.session_family_id
          FROM user_sessions s
         WHERE rt.session_id IS NULL
           AND s.id = rt.session_family_id;

        COMMIT;
        EXIT WHEN touched = 0;
    END LOOP;
END $$;

-- +goose StatementEnd

-- +goose StatementBegin

CALL emc_backfill_user_sessions();

-- +goose StatementEnd

-- +goose StatementBegin

DROP PROCEDURE IF EXISTS emc_backfill_user_sessions();

-- +goose StatementEnd

-- +goose StatementBegin

-- Advance the identity sequence past every explicitly-inserted id, or the first
-- new session would collide with a backfilled one.
SELECT setval(
    pg_get_serial_sequence('user_sessions', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 0) FROM user_sessions), 1)
);

-- +goose StatementEnd

-- +goose StatementBegin

-- Serves the session list and the active-session count: one row per session now,
-- so neither needs DISTINCT ON over a rotation log.
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_user_sessions_live
    ON user_sessions (user_id, tenant_id, last_seen_at DESC)
    WHERE revoked_at IS NULL;

-- +goose StatementEnd

-- +goose StatementBegin

-- Serves the token → session join on every refresh.
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_refresh_tokens_session
    ON refresh_tokens (session_id);

-- +goose StatementEnd

-- +goose StatementBegin

-- Serves the reaper.
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_user_sessions_reap
    ON user_sessions (absolute_expires_at);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP INDEX CONCURRENTLY IF EXISTS idx_user_sessions_reap;

-- +goose StatementEnd

-- +goose StatementBegin

DROP INDEX CONCURRENTLY IF EXISTS idx_refresh_tokens_session;

-- +goose StatementEnd

-- +goose StatementBegin

DROP INDEX CONCURRENTLY IF EXISTS idx_user_sessions_live;

-- +goose StatementEnd

-- +goose StatementBegin

-- Safe to reverse: refresh_tokens keeps session_family_id and its own lifecycle
-- columns, which the previous binary reads, so rolling back the code works without
-- restoring data. Only the parent rows are lost.
ALTER TABLE refresh_tokens DROP COLUMN IF EXISTS session_id;
DROP TABLE IF EXISTS user_sessions;

-- +goose StatementEnd
