-- +goose Up
-- +goose StatementBegin

-- WebAuthn / passkey credentials (spike slice — see docs/WEBAUTHN_PLAN.md).
--
-- A passkey is a public-key credential held by an authenticator (Windows Hello,
-- iCloud Keychain, Google Password Manager, a security key). The private key
-- never leaves the authenticator, so unlike every other credential in this
-- schema there is no secret here for us to protect — only material we must not
-- confuse between users, tenants, or relying parties.
--
-- Nothing in this table is hashed, which is a deliberate exception to
-- non-negotiable #1 ("never store raw tokens") and is called out here so a
-- reader does not take it for an oversight:
--
--   * public_key is a public key. It is public by construction.
--   * credential_id must be returned VERBATIM to the browser in
--     allowCredentials for non-discoverable authenticators to work at all.
--     Hashing it would break the protocol, not harden it.
--
-- The security properties of this table come from scoping, not secrecy: every
-- lookup is filtered by tenant_id AND rp_id, and the browser independently
-- refuses a credential whose rp_id does not match the page's origin.

CREATE TABLE IF NOT EXISTS webauthn_credentials (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id          BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tenant_id        BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    -- Which application the credential was registered through. NULL for a
    -- tenant-level surface (the admin console), matching user_sessions.
    application_id   BIGINT REFERENCES oauth_clients(id) ON DELETE CASCADE,

    -- The Relying Party ID the credential was created for: the registrable
    -- domain of the page that ran the ceremony.
    --
    -- NOT NULL and part of every lookup. A credential created for one RP ID
    -- must never be offered in another RP's ceremony — the browser would refuse
    -- it anyway, so offering it produces a dead end the user cannot explain
    -- rather than a security hole. Filtering here is what keeps the two
    -- surfaces (tenant app domain vs hosted login) honestly separate.
    rp_id            TEXT   NOT NULL,

    credential_id    BYTEA  NOT NULL,   -- raw; goes back out in allowCredentials
    public_key       BYTEA  NOT NULL,   -- COSE_Key, as returned by the authenticator
    aaguid           BYTEA,             -- authenticator model id ('none' attestation → zeroes
    attestation_type TEXT   NOT NULL DEFAULT 'none',
    transports       TEXT[] NOT NULL DEFAULT '{}',

    -- Cloned-authenticator detection. A counter that fails to advance on a
    -- credential that was previously counting means two copies of the private
    -- key may exist. Many platform authenticators (Apple, Google) legitimately
    -- always report 0, so "0 both sides" is normal and must NOT be treated as a
    -- regression — only a decrease from a non-zero stored value is.
    sign_count       BIGINT NOT NULL DEFAULT 0,

    -- Backup Eligible / Backup State.
    --
    -- backup_eligible says the credential MAY sync between devices and is fixed
    -- for the life of the credential — if it ever changes, the authenticator has
    -- been cloned or swapped, and that is a hard rejection.
    --
    -- backup_state says whether it currently IS synced, and may flip freely.
    -- It is what tells a user (and support) whether this passkey survives losing
    -- the device: a Windows Hello credential is device-bound and dies with the
    -- laptop, an iCloud Keychain or Google Password Manager one does not.
    backup_eligible  BOOLEAN NOT NULL DEFAULT false,
    backup_state     BOOLEAN NOT NULL DEFAULT false,

    -- Whether the authenticator performed user verification (biometric/PIN) at
    -- registration. In a passwordless sign-in the gesture is the second factor,
    -- so this is what lets the issued token claim 'mfa' honestly.
    uv_capable       BOOLEAN NOT NULL DEFAULT false,

    -- Whether the credential came back DISCOVERABLE (a resident key). Only
    -- discoverable credentials appear in browser autofill, so a
    -- non-discoverable one is a credential the user will never see offered —
    -- recorded so that failure is visible in the data rather than mysterious in
    -- the UI.
    discoverable     BOOLEAN NOT NULL DEFAULT false,

    name             TEXT   NOT NULL DEFAULT '',   -- user-facing label
    -- Soft-delete, per non-negotiable #5's reasoning: which passkey was removed
    -- and when is audit-relevant, so the row stays.
    is_active        BOOLEAN NOT NULL DEFAULT true,

    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at     TIMESTAMPTZ,
    last_used_ip     INET
);

-- A credential ID identifies exactly one authenticator credential. Uniqueness is
-- global rather than per-user: it stops one authenticator credential being
-- claimed by two accounts, and it is what makes discoverable login resolvable at
-- all, since the assertion arrives carrying only a credential ID and that must
-- name exactly one row.
--
-- Partial on is_active, which is the part that is easy to get wrong. Revocation
-- here is a soft delete, so a plain unique index over every row would burn the
-- credential ID permanently: a user who removed a passkey and then tried to
-- enrol the same device again would hit a unique violation and be told the
-- passkey is "already registered" — referring to a row they cannot see and
-- cannot use. Scoping uniqueness to live rows makes re-enrolment work while
-- keeping the revoked row for the audit trail.
CREATE UNIQUE INDEX IF NOT EXISTS uq_webauthn_credential_id
    ON webauthn_credentials (credential_id) WHERE is_active;

-- The registration/second-factor lookup: "which credentials does this user have
-- for this relying party?"
CREATE INDEX IF NOT EXISTS idx_webauthn_creds_user_rp
    ON webauthn_credentials (user_id, rp_id) WHERE is_active;

CREATE INDEX IF NOT EXISTS idx_webauthn_creds_tenant
    ON webauthn_credentials (tenant_id);

-- The WebAuthn user handle: an opaque per-user identifier stored ON THE
-- AUTHENTICATOR and returned with every discoverable assertion.
--
-- A separate table rather than a column on users because it is not a property
-- of the account, it is a property of the account's relationship to WebAuthn —
-- and because users is the hottest table in the schema and does not need
-- another column for a feature most rows will never use.
--
-- It must be random, stable, and opaque. Not the email (it is displayed in some
-- authenticator UIs and would leak PII to anyone with the device), and not the
-- integer primary key (it would be enumerable and would leak how many users
-- exist). One handle per user, shared by all their credentials, so the
-- authenticator groups them under one account.
CREATE TABLE IF NOT EXISTS webauthn_user_handles (
    user_id    BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    tenant_id  BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    handle     BYTEA  NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_webauthn_user_handle
    ON webauthn_user_handles (handle);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP TABLE IF EXISTS webauthn_user_handles;
DROP TABLE IF EXISTS webauthn_credentials;

-- +goose StatementEnd
